FROM node:lts-alpine as build
WORKDIR /app
COPY package*.json ./
# RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
# RUN cnpm install
RUN npm install
COPY . .
RUN npm run build:prod

FROM nginx
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/ /usr/share/nginx/html/